In [1]:
from statsmodels.regression.rolling import RollingOLS
import pandas_datareader.data as web
import matplotlib.pyplot as plt
import statsmodels.api as sm
import pandas as pd
import numpy as np
import datetime as dt
import yfinance as yf
import pandas_ta
import warnings

In [2]:
warnings.filterwarnings('ignore')

In [3]:
import io
import requests

headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'}
url = 'https://en.wikipedia.org/wiki/List_of_S%26P_500_companies'
response = requests.get(url, headers=headers)

sp500 = pd.read_html(io.StringIO(response.text))[0]
sp500['Symbol'] = sp500['Symbol'].str.replace('.', '-')
symbols_list = sp500['Symbol'].unique().tolist()

In [5]:
end_date = '2026-08-13'
start_date = pd.to_datetime(end_date) - pd.DateOffset(365*8)
df = yf.download(tickers=symbols_list,
                 start=start_date,
                 end=end_date).stack()
df.index.names = ['date', 'ticker']
df.columns = df.columns.str.lower()
df.to_pickle('data/01_raw.pkl')

[*********************100%***********************]  503 of 503 completed

In [6]:
df

Price                   close        high         low        open       volume
date       ticker
2018-08-15 A        60.991581   62.555705   60.511034   62.131698    6071500.0
           AAPL     49.666737   49.784856   49.215521   49.425773  115230400.0
           ABBV     69.514221   69.756757   68.201693   68.422824    6861500.0
           ABNB           NaN         NaN         NaN         NaN          NaN
           ABT      54.906963   54.984821   54.560928   54.889661    3724900.0
...                       ...         ...         ...         ...          ...
2026-08-12 XYZ      78.279999   79.199997   77.230003   78.580002    4343100.0
           YUM     150.339996  150.389999  144.429993  144.610001    3080700.0
           ZBH      97.889999   97.940002   94.279999   95.690002    2733600.0
           ZBRA    378.369995  386.230011  374.019989  384.230011     748500.0
           ZTS      73.540001   74.389999   71.989998   74.389999    7186400.0

[1010024 rows x 5 columns]

In [7]:
print(df.shape)
df.head()

(1010024, 5)

Price                  close       high        low       open       volume
date       ticker
2018-08-15 A       60.991581  62.555705  60.511034  62.131698    6071500.0
           AAPL    49.666737  49.784856  49.215521  49.425773  115230400.0
           ABBV    69.514221  69.756757  68.201693  68.422824    6861500.0
           ABNB          NaN        NaN        NaN        NaN          NaN
           ABT     54.906963  54.984821  54.560928  54.889661    3724900.0

In [ ]:
df.to_pickle('data/01_raw.pkl')