In [1]:
import pandas as pd

In [2]:
df = pd.read_pickle('data/01_raw.pkl')
df

Price                   close        high         low        open       volume
date       ticker
2018-08-15 A        60.991581   62.555705   60.511034   62.131698    6071500.0
           AAPL     49.666737   49.784856   49.215521   49.425773  115230400.0
           ABBV     69.514221   69.756757   68.201693   68.422824    6861500.0
           ABNB           NaN         NaN         NaN         NaN          NaN
           ABT      54.906963   54.984821   54.560928   54.889661    3724900.0
...                       ...         ...         ...         ...          ...
2026-08-12 XYZ      78.279999   79.199997   77.230003   78.580002    4343100.0
           YUM     150.339996  150.389999  144.429993  144.610001    3080700.0
           ZBH      97.889999   97.940002   94.279999   95.690002    2733600.0
           ZBRA    378.369995  386.230011  374.019989  384.230011     748500.0
           ZTS      73.540001   74.389999   71.989998   74.389999    7186400.0

[1010024 rows x 5 columns]

In [3]:
print(df.shape)
df.head()

(1010024, 5)

Price                  close       high        low       open       volume
date       ticker
2018-08-15 A       60.991581  62.555705  60.511034  62.131698    6071500.0
           AAPL    49.666737  49.784856  49.215521  49.425773  115230400.0
           ABBV    69.514221  69.756757  68.201693  68.422824    6861500.0
           ABNB          NaN        NaN        NaN        NaN          NaN
           ABT     54.906963  54.984821  54.560928  54.889661    3724900.0

In [4]:
import numpy as np
import pandas

In [5]:
df['garman_klass_vol'] = ((np.log(df['high'])-np.log(df['low']))**2)/2-(2*np.log(2)-1)*((np.log(df['close'])-np.log(df['open']))**2)

In [6]:
df

Price                   close        high         low        open  \
date       ticker
2018-08-15 A        60.991581   62.555705   60.511034   62.131698
           AAPL     49.666737   49.784856   49.215521   49.425773
           ABBV     69.514221   69.756757   68.201693   68.422824
           ABNB           NaN         NaN         NaN         NaN
           ABT      54.906963   54.984821   54.560928   54.889661
...                       ...         ...         ...         ...
2026-08-12 XYZ      78.279999   79.199997   77.230003   78.580002
           YUM     150.339996  150.389999  144.429993  144.610001
           ZBH      97.889999   97.940002   94.279999   95.690002
           ZBRA    378.369995  386.230011  374.019989  384.230011
           ZTS      73.540001   74.389999   71.989998   74.389999

Price                   volume  garman_klass_vol
date       ticker
2018-08-15 A         6071500.0          0.000420
           AAPL    115230400.0          0.000057
           ABBV      6861500.0          0.000157
           ABNB            NaN               NaN
           ABT       3724900.0          0.000030
...                        ...               ...
2026-08-12 XYZ       4343100.0          0.000312
           YUM       3080700.0          0.000234
           ZBH       2733600.0          0.000526
           ZBRA       748500.0          0.000425
           ZTS       7186400.0          0.000487

[1010024 rows x 6 columns]

In [7]:
import pandas_ta

In [8]:
df['rsi'] = df.groupby(level=1)['close'].transform(lambda x: pandas_ta.rsi(close=x, length=20))

In [9]:
df

Price                   close        high         low        open  \
date       ticker
2018-08-15 A        60.991581   62.555705   60.511034   62.131698
           AAPL     49.666737   49.784856   49.215521   49.425773
           ABBV     69.514221   69.756757   68.201693   68.422824
           ABNB           NaN         NaN         NaN         NaN
           ABT      54.906963   54.984821   54.560928   54.889661
...                       ...         ...         ...         ...
2026-08-12 XYZ      78.279999   79.199997   77.230003   78.580002
           YUM     150.339996  150.389999  144.429993  144.610001
           ZBH      97.889999   97.940002   94.279999   95.690002
           ZBRA    378.369995  386.230011  374.019989  384.230011
           ZTS      73.540001   74.389999   71.989998   74.389999

Price                   volume  garman_klass_vol        rsi
date       ticker
2018-08-15 A         6071500.0          0.000420        NaN
           AAPL    115230400.0          0.000057        NaN
           ABBV      6861500.0          0.000157        NaN
           ABNB            NaN               NaN        NaN
           ABT       3724900.0          0.000030        NaN
...                        ...               ...        ...
2026-08-12 XYZ       4343100.0          0.000312  49.935831
           YUM       3080700.0          0.000234  47.965239
           ZBH       2733600.0          0.000526  59.070244
           ZBRA       748500.0          0.000425  78.001656
           ZTS       7186400.0          0.000487  43.338929

[1010024 rows x 7 columns]

In [10]:
df['bb_low'] = df.groupby(level=1)['close'].transform(lambda x: pandas_ta.bbands(close=np.log1p(x), length=20).iloc[:,0])

df['bb_mid'] = df.groupby(level=1)['close'].transform(lambda x: pandas_ta.bbands(close=np.log1p(x), length=20).iloc[:,1])

df['bb_high'] = df.groupby(level=1)['close'].transform(lambda x: pandas_ta.bbands(close=np.log1p(x), length=20).iloc[:,2])

In [11]:
df

Price                   close        high         low        open  \
date       ticker
2018-08-15 A        60.991581   62.555705   60.511034   62.131698
           AAPL     49.666737   49.784856   49.215521   49.425773
           ABBV     69.514221   69.756757   68.201693   68.422824
           ABNB           NaN         NaN         NaN         NaN
           ABT      54.906963   54.984821   54.560928   54.889661
...                       ...         ...         ...         ...
2026-08-12 XYZ      78.279999   79.199997   77.230003   78.580002
           YUM     150.339996  150.389999  144.429993  144.610001
           ZBH      97.889999   97.940002   94.279999   95.690002
           ZBRA    378.369995  386.230011  374.019989  384.230011
           ZTS      73.540001   74.389999   71.989998   74.389999

Price                   volume  garman_klass_vol        rsi    bb_low  \
date       ticker
2018-08-15 A         6071500.0          0.000420        NaN       NaN
           AAPL    115230400.0          0.000057        NaN       NaN
           ABBV      6861500.0          0.000157        NaN       NaN
           ABNB            NaN               NaN        NaN       NaN
           ABT       3724900.0          0.000030        NaN       NaN
...                        ...               ...        ...       ...
2026-08-12 XYZ       4343100.0          0.000312  49.935831  4.342263
           YUM       3080700.0          0.000234  47.965239  4.974626
           ZBH       2733600.0          0.000526  59.070244  4.485455
           ZBRA       748500.0          0.000425  78.001656  5.402393
           ZTS       7186400.0          0.000487  43.338929  4.303346

Price                bb_mid   bb_high
date       ticker
2018-08-15 A            NaN       NaN
           AAPL         NaN       NaN
           ABBV         NaN       NaN
           ABNB         NaN       NaN
           ABT          NaN       NaN
...                     ...       ...
2026-08-12 XYZ     4.398908  4.455553
           YUM     5.014113  5.053600
           ZBH     4.555733  4.626010
           ZBRA    5.721512  6.040631
           ZTS     4.340344  4.377342

[1010024 rows x 10 columns]

In [12]:
def compute_atr(stock_data):
    atr = pandas_ta.atr(high=stock_data['high'],
                        low=stock_data['low'],
                        close=stock_data['close'],
                        length=14)
    return atr.sub(atr.mean()).div(atr.std())

In [13]:
df['atr'] = df.groupby(level=1, group_keys=False).apply(compute_atr)

In [14]:
def compute_macd(close):
    macd = pandas_ta.macd(close=close, length=20).iloc[:,0]
    return macd.sub(macd.mean()).div(macd.std())

In [15]:
df['macd'] = df.groupby(level=1, group_keys=False)['close'].apply(compute_macd)

In [16]:
df['dollar_volume'] = (df['close']*df['volume'])/1e6

In [17]:
df

Price                   close        high         low        open  \
date       ticker
2018-08-15 A        60.991581   62.555705   60.511034   62.131698
           AAPL     49.666737   49.784856   49.215521   49.425773
           ABBV     69.514221   69.756757   68.201693   68.422824
           ABNB           NaN         NaN         NaN         NaN
           ABT      54.906963   54.984821   54.560928   54.889661
...                       ...         ...         ...         ...
2026-08-12 XYZ      78.279999   79.199997   77.230003   78.580002
           YUM     150.339996  150.389999  144.429993  144.610001
           ZBH      97.889999   97.940002   94.279999   95.690002
           ZBRA    378.369995  386.230011  374.019989  384.230011
           ZTS      73.540001   74.389999   71.989998   74.389999

Price                   volume  garman_klass_vol        rsi    bb_low  \
date       ticker
2018-08-15 A         6071500.0          0.000420        NaN       NaN
           AAPL    115230400.0          0.000057        NaN       NaN
           ABBV      6861500.0          0.000157        NaN       NaN
           ABNB            NaN               NaN        NaN       NaN
           ABT       3724900.0          0.000030        NaN       NaN
...                        ...               ...        ...       ...
2026-08-12 XYZ       4343100.0          0.000312  49.935831  4.342263
           YUM       3080700.0          0.000234  47.965239  4.974626
           ZBH       2733600.0          0.000526  59.070244  4.485455
           ZBRA       748500.0          0.000425  78.001656  5.402393
           ZTS       7186400.0          0.000487  43.338929  4.303346

Price                bb_mid   bb_high       atr      macd  dollar_volume
date       ticker
2018-08-15 A            NaN       NaN       NaN       NaN     370.310384
           AAPL         NaN       NaN       NaN       NaN    5723.117925
           ABBV         NaN       NaN       NaN       NaN     476.971829
           ABNB         NaN       NaN       NaN       NaN            NaN
           ABT          NaN       NaN       NaN       NaN     204.522948
...                     ...       ...       ...       ...            ...
2026-08-12 XYZ     4.398908  4.455553 -0.668036  0.144249     339.977863
           YUM     5.014113  5.053600  3.248934 -1.234277     463.152427
           ZBH     4.555733  4.626010  0.354879  0.997090     267.592102
           ZBRA    5.721512  6.040631  1.556197  3.605673     283.209941
           ZTS     4.340344  4.377342 -0.398774 -0.195375     528.487863

[1010024 rows x 13 columns]

In [18]:
df.to_pickle('data/02_indicators.pkl')